Repository mozilla/fx-private-relay-add-on, pull requests merged in 2023-08, with the labels that each got.

#513 Documentation update
  README.md
Labels: documentation

#462 Change icon: overlaid button to background image
  .eslintrc.js
  src/js/other-websites/add_input_icon.js
  src/js/other-websites/email_detector.js
  src/js/other-websites/fill_relay_address.js
  src/js/other-websites/icon.js
  src/manifest.json
Labels: web-compat

#517 MPP-3368
  src/js/popup/popup.js
Labels: :bug: bug
